#include "File.h"

std::string GetOutputFileName()
{
	char AppPath[MAX_PATH] = { 0 };
	GetCurrentDirectoryA(MAX_PATH, AppPath);
	std::string outPath = AppPath;
	outPath += "\\Snap.Hutao Error Log.txt";
	return outPath;
}

void InitializeOutputFile()
{
	std::ofstream fs;
	fs.open(GetOutputFileName().c_str());
	fs << "Generated by Snap Hutao Diagnosis Tool" << std::endl;
	fs << "--------------------------------------" << std::endl;
	fs.close();
}

void AppendToOutputFile(std::string content)
{
	std::ofstream fs;
	fs.open(GetOutputFileName().c_str(), std::ios::app);
	fs << content;
	fs.close();
}